### ISSUE TITLE
Basic Subsystem Setup -- Climber

### ISSUE THREAD

**Issue by Sam-Malta** [cavineers/RobotCode2024#10]
Basic Functions moving motors, as well as other basic methods + constructors.

Just keep this thread updated with delays or done features. @ashley064

**Comment by ashley064** [comment]
Progress:
We completed a draft of the following code:
- RightClimber.java
- LeftClimber.java
- RiseClimberCommand.java
- LowerClmberCommand.java

Next steps:
- Hooking up the commands to buttons on the controller 
- Entering the testing phase to identify bugs and refine the code

**Comment by Sam-Malta** [comment]
Completed 1.27

**Comment by ashley064** [comment]
1/27/24 Update:
- We started testing the RiseClimberCommand code on the test board and realized that both bumpers were controlling different motors.
- To fix this, we added additional if statements in the isFinished() and end() methods.
- We fixed an issue where the limit switches in the subsystems were declared as private instead of public.
- We are currently working toward fixing an issue with "squeaky" right motor movement.

**Comment by ashley064** [comment]
1/31/24 Update:
- Today we tested the rise climber command and it worked! The issue was that the test board did not originally contain limit switches. Another issue was that we used the onTrue command instead of the whileTrue command to run commands upon button press.

Next steps:
- Talk to mechanical about whether or not we will use a limit switch at the bottom as well as the top.
- Update the command used to make buttons.
- Test the lower climber command.

**Comment by ashley064** [comment]
2/1/24 Update:
- At the end of last meeting, we learned that each climber will have two limit switches (one on the top and one on the bottom).
- Included an extra limit switch in each subsystem (the left and right climbers) to accomodate using two limit switches. 
- Added a parameter for the getLimitSwitch function that specifies if the function should return the state of the upper or lower limit switch for a given climber.

Testing description:
- After the changes above were made, the only command that worked was the command for raising the left climber.
- It was found that the second condition of the if statement in the rise climber command (the part of the if statement that runs the motor when the limit switch is NOT on) was not running, even though the limit switch was not activated. Further testing is needed.

**Comment by ashley064** [comment]
2/5/24 Update:

- We fixed the if statements that control the actions of the right climber in the rising and lowering commands to match the logic followed by the left climber (which worked).
- We tested the rising and lowering commands for both the left and right climber with limit switches, and the code worked as expected. 
- Started the process for a pull request.
